import type {
  EvCharger,
  EvChargerList,
  GetEvChargersNearParams,
} from "./types";
import { getDistanceKm } from "./place.data";

const mockEvChargers: EvCharger[] = [
  {
    id: "charger-tyler-broadway-supercharge",
    name: "Broadway EV Supercharge",
    operatorName: "Navio Charge",
    location: {
      lat: 32.2796,
      lng: -95.3049,
      address: "4815 S Broadway Ave, Tyler, TX 75703, USA",
      placeId: "mock-charger-tyler-broadway",
    },
    address: "4815 S Broadway Ave, Tyler, TX 75703, USA",
    province: "Texas",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 120,
    totalConnectors: 8,
    availableConnectors: 5,
    priceText: "$0.36/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.6,
    ratingCount: 42,
    confidenceScore: 0.94,
    stale: false,
  },
  {
    id: "charger-tyler-loop-fast-charge",
    name: "Loop 323 Fast Charge",
    operatorName: "VoltWay",
    location: {
      lat: 32.3228,
      lng: -95.3332,
      address: "2180 WSW Loop 323, Tyler, TX 75701, USA",
      placeId: "mock-charger-tyler-loop",
    },
    address: "2180 WSW Loop 323, Tyler, TX 75701, USA",
    province: "Texas",
    connectorTypes: ["CCS2", "CHADEMO"],
    maxKw: 150,
    totalConnectors: 6,
    availableConnectors: 2,
    priceText: "$0.42/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.3,
    ratingCount: 31,
    confidenceScore: 0.86,
    stale: false,
  },
  {
    id: "charger-tyler-downtown-type2",
    name: "Downtown Tyler Charge Point",
    operatorName: "City Parking",
    location: {
      lat: 32.3511,
      lng: -95.3006,
      address: "120 N College Ave, Tyler, TX 75702, USA",
      placeId: "mock-charger-tyler-downtown",
    },
    address: "120 N College Ave, Tyler, TX 75702, USA",
    province: "Texas",
    connectorTypes: ["TYPE2"],
    maxKw: 22,
    totalConnectors: 4,
    availableConnectors: 1,
    priceText: "Free for first 2 hours",
    openingHours: { summary: "6:00 AM - 11:00 PM" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.1,
    ratingCount: 18,
    confidenceScore: 0.78,
    stale: false,
  },
  {
    id: "charger-dallas-main-hub",
    name: "Main Street Charging Hub",
    operatorName: "Electra",
    location: {
      lat: 32.7755,
      lng: -96.7991,
      address: "132 Main Street, Dallas, TX 75201, USA",
      placeId: "mock-charger-dallas-main",
    },
    address: "132 Main Street, Dallas, TX 75201, USA",
    province: "Texas",
    connectorTypes: ["CCS2", "NACS"],
    maxKw: 250,
    totalConnectors: 12,
    availableConnectors: 7,
    priceText: "$0.45/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.7,
    ratingCount: 89,
    confidenceScore: 0.97,
    stale: false,
  },
  {
    id: "charger-plano-preston-rapid",
    name: "Preston Rapid Charge",
    operatorName: "ChargeGrid",
    location: {
      lat: 33.0753,
      lng: -96.7953,
      address: "7120 Preston Rd, Plano, TX 75024, USA",
      placeId: "mock-charger-plano-preston",
    },
    address: "7120 Preston Rd, Plano, TX 75024, USA",
    province: "Texas",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 180,
    totalConnectors: 10,
    availableConnectors: 4,
    priceText: "$0.39/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.4,
    ratingCount: 53,
    confidenceScore: 0.88,
    stale: false,
  },
  {
    id: "charger-austin-congress-fast",
    name: "Congress Avenue EV Fast Stop",
    operatorName: "Navio Charge",
    location: {
      lat: 30.2695,
      lng: -97.744,
      address: "620 Congress Ave, Austin, TX 78701, USA",
      placeId: "mock-charger-austin-congress",
    },
    address: "620 Congress Ave, Austin, TX 78701, USA",
    province: "Texas",
    connectorTypes: ["CCS2", "NACS"],
    maxKw: 200,
    totalConnectors: 8,
    availableConnectors: 3,
    priceText: "$0.41/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.5,
    ratingCount: 66,
    confidenceScore: 0.93,
    stale: false,
  },
  {
    id: "charger-bangkok-siam-rapid",
    name: "Siam Rapid Charge",
    operatorName: "EA Anywhere",
    location: {
      lat: 13.7466,
      lng: 100.5347,
      address: "Rama I Rd, Pathum Wan, Bangkok 10330, Thailand",
      placeId: "mock-charger-bangkok-siam",
    },
    address: "Rama I Rd, Pathum Wan, Bangkok 10330, Thailand",
    province: "Bangkok",
    connectorTypes: ["CCS2", "CHADEMO", "TYPE2"],
    maxKw: 120,
    totalConnectors: 10,
    availableConnectors: 6,
    priceText: "THB 8.50/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.6,
    ratingCount: 74,
    confidenceScore: 0.95,
    stale: false,
  },
  {
    id: "charger-bangkok-riverside",
    name: "Riverside EV Station",
    operatorName: "PEA Volta",
    location: {
      lat: 13.7311,
      lng: 100.5142,
      address: "Charoen Krung Rd, Bang Rak, Bangkok 10500, Thailand",
      placeId: "mock-charger-bangkok-riverside",
    },
    address: "Charoen Krung Rd, Bang Rak, Bangkok 10500, Thailand",
    province: "Bangkok",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 80,
    totalConnectors: 6,
    availableConnectors: 2,
    priceText: "THB 7.90/kWh",
    openingHours: { summary: "7:00 AM - 11:00 PM" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.2,
    ratingCount: 19,
    confidenceScore: 0.8,
    stale: false,
  },
  {
    id: "charger-bangkok-asoke-terminal",
    name: "Asoke Terminal EV Hub",
    operatorName: "EA Anywhere",
    location: {
      lat: 13.7373,
      lng: 100.5601,
      address: "Sukhumvit Rd, Watthana, Bangkok 10110, Thailand",
      placeId: "mock-charger-bangkok-asoke-terminal",
    },
    address: "Sukhumvit Rd, Watthana, Bangkok 10110, Thailand",
    province: "Bangkok",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 150,
    totalConnectors: 12,
    availableConnectors: 7,
    priceText: "THB 8.90/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.7,
    ratingCount: 128,
    confidenceScore: 0.96,
    stale: false,
  },
  {
    id: "charger-bangkok-ladprao-mall",
    name: "Lat Phrao Mall Charge Point",
    operatorName: "PEA Volta",
    location: {
      lat: 13.8162,
      lng: 100.5616,
      address: "Phahonyothin Rd, Chatuchak, Bangkok 10900, Thailand",
      placeId: "mock-charger-bangkok-ladprao-mall",
    },
    address: "Phahonyothin Rd, Chatuchak, Bangkok 10900, Thailand",
    province: "Bangkok",
    connectorTypes: ["CCS2", "CHADEMO", "TYPE2"],
    maxKw: 120,
    totalConnectors: 10,
    availableConnectors: 4,
    priceText: "THB 8.20/kWh",
    openingHours: { summary: "10:00 AM - 10:00 PM" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.4,
    ratingCount: 83,
    confidenceScore: 0.88,
    stale: false,
  },
  {
    id: "charger-bangkok-thonglor-fast",
    name: "Thonglor Fast Charge",
    operatorName: "VoltWay",
    location: {
      lat: 13.7306,
      lng: 100.5827,
      address: "Thong Lo Rd, Watthana, Bangkok 10110, Thailand",
      placeId: "mock-charger-bangkok-thonglor-fast",
    },
    address: "Thong Lo Rd, Watthana, Bangkok 10110, Thailand",
    province: "Bangkok",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 180,
    totalConnectors: 8,
    availableConnectors: 3,
    priceText: "THB 9.00/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.5,
    ratingCount: 47,
    confidenceScore: 0.84,
    stale: false,
  },
  {
    id: "charger-nonthaburi-central-westgate",
    name: "Central Westgate EV Station",
    operatorName: "EA Anywhere",
    location: {
      lat: 13.8764,
      lng: 100.4112,
      address: "Bang Yai, Nonthaburi 11140, Thailand",
      placeId: "mock-charger-nonthaburi-central-westgate",
    },
    address: "Bang Yai, Nonthaburi 11140, Thailand",
    province: "Nonthaburi",
    connectorTypes: ["CCS2", "CHADEMO", "TYPE2"],
    maxKw: 160,
    totalConnectors: 14,
    availableConnectors: 8,
    priceText: "THB 8.50/kWh",
    openingHours: { summary: "10:00 AM - 10:00 PM" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.6,
    ratingCount: 101,
    confidenceScore: 0.95,
    stale: false,
  },
  {
    id: "charger-pathum-thani-rangsit",
    name: "Rangsit Future Charge Hub",
    operatorName: "PEA Volta",
    location: {
      lat: 13.9888,
      lng: 100.6176,
      address: "Rangsit, Pathum Thani 12130, Thailand",
      placeId: "mock-charger-pathum-thani-rangsit",
    },
    address: "Rangsit, Pathum Thani 12130, Thailand",
    province: "Pathum Thani",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 120,
    totalConnectors: 10,
    availableConnectors: 5,
    priceText: "THB 8.30/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.3,
    ratingCount: 58,
    confidenceScore: 0.87,
    stale: false,
  },
  {
    id: "charger-samut-prakan-bangna",
    name: "Bang Na Express EV Stop",
    operatorName: "Navio Charge",
    location: {
      lat: 13.6674,
      lng: 100.6432,
      address: "Bang Na-Trat Rd, Samut Prakan 10270, Thailand",
      placeId: "mock-charger-samut-prakan-bangna",
    },
    address: "Bang Na-Trat Rd, Samut Prakan 10270, Thailand",
    province: "Samut Prakan",
    connectorTypes: ["CCS2", "NACS", "TYPE2"],
    maxKw: 250,
    totalConnectors: 12,
    availableConnectors: 6,
    priceText: "THB 9.20/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.7,
    ratingCount: 92,
    confidenceScore: 0.96,
    stale: false,
  },
  {
    id: "charger-ayutthaya-historical-park",
    name: "Ayutthaya Heritage EV Point",
    operatorName: "PEA Volta",
    location: {
      lat: 14.3559,
      lng: 100.5689,
      address: "Phra Nakhon Si Ayutthaya 13000, Thailand",
      placeId: "mock-charger-ayutthaya-historical-park",
    },
    address: "Phra Nakhon Si Ayutthaya 13000, Thailand",
    province: "Phra Nakhon Si Ayutthaya",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 80,
    totalConnectors: 6,
    availableConnectors: 2,
    priceText: "THB 7.90/kWh",
    openingHours: { summary: "7:00 AM - 9:00 PM" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.2,
    ratingCount: 35,
    confidenceScore: 0.82,
    stale: false,
  },
  {
    id: "charger-nakhon-pathom-phra-pathom",
    name: "Nakhon Pathom City Charge",
    operatorName: "VoltWay",
    location: {
      lat: 13.8199,
      lng: 100.0621,
      address: "Mueang Nakhon Pathom, Nakhon Pathom 73000, Thailand",
      placeId: "mock-charger-nakhon-pathom-phra-pathom",
    },
    address: "Mueang Nakhon Pathom, Nakhon Pathom 73000, Thailand",
    province: "Nakhon Pathom",
    connectorTypes: ["CCS2", "CHADEMO"],
    maxKw: 100,
    totalConnectors: 6,
    availableConnectors: 4,
    priceText: "THB 8.00/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.3,
    ratingCount: 41,
    confidenceScore: 0.86,
    stale: false,
  },
  {
    id: "charger-kanchanaburi-river-kwai",
    name: "River Kwai EV Station",
    operatorName: "PEA Volta",
    location: {
      lat: 14.0396,
      lng: 99.5033,
      address: "Mueang Kanchanaburi, Kanchanaburi 71000, Thailand",
      placeId: "mock-charger-kanchanaburi-river-kwai",
    },
    address: "Mueang Kanchanaburi, Kanchanaburi 71000, Thailand",
    province: "Kanchanaburi",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 100,
    totalConnectors: 6,
    availableConnectors: 3,
    priceText: "THB 8.10/kWh",
    openingHours: { summary: "6:00 AM - 10:00 PM" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.4,
    ratingCount: 52,
    confidenceScore: 0.91,
    stale: false,
  },
  {
    id: "charger-hua-hin-beachfront",
    name: "Hua Hin Beachfront Charge",
    operatorName: "EA Anywhere",
    location: {
      lat: 12.5684,
      lng: 99.9577,
      address: "Hua Hin, Prachuap Khiri Khan 77110, Thailand",
      placeId: "mock-charger-hua-hin-beachfront",
    },
    address: "Hua Hin, Prachuap Khiri Khan 77110, Thailand",
    province: "Prachuap Khiri Khan",
    connectorTypes: ["CCS2", "CHADEMO", "TYPE2"],
    maxKw: 150,
    totalConnectors: 10,
    availableConnectors: 5,
    priceText: "THB 8.70/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.6,
    ratingCount: 77,
    confidenceScore: 0.94,
    stale: false,
  },
  {
    id: "charger-pattaya-beach-road",
    name: "Pattaya Beach Road EV Hub",
    operatorName: "VoltWay",
    location: {
      lat: 12.9276,
      lng: 100.8771,
      address: "Beach Rd, Pattaya, Chonburi 20150, Thailand",
      placeId: "mock-charger-pattaya-beach-road",
    },
    address: "Beach Rd, Pattaya, Chonburi 20150, Thailand",
    province: "Chonburi",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 180,
    totalConnectors: 12,
    availableConnectors: 6,
    priceText: "THB 8.90/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.5,
    ratingCount: 96,
    confidenceScore: 0.9,
    stale: false,
  },
  {
    id: "charger-rayong-city-fast",
    name: "Rayong City Fast Charge",
    operatorName: "PEA Volta",
    location: {
      lat: 12.6814,
      lng: 101.2816,
      address: "Mueang Rayong, Rayong 21000, Thailand",
      placeId: "mock-charger-rayong-city-fast",
    },
    address: "Mueang Rayong, Rayong 21000, Thailand",
    province: "Rayong",
    connectorTypes: ["CCS2", "CHADEMO"],
    maxKw: 120,
    totalConnectors: 8,
    availableConnectors: 3,
    priceText: "THB 8.40/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.4,
    ratingCount: 48,
    confidenceScore: 0.91,
    stale: false,
  },
  {
    id: "charger-trat-koh-chang-pier",
    name: "Trat Pier EV Stop",
    operatorName: "PEA Volta",
    location: {
      lat: 12.1967,
      lng: 102.5151,
      address: "Laem Ngop, Trat 23120, Thailand",
      placeId: "mock-charger-trat-koh-chang-pier",
    },
    address: "Laem Ngop, Trat 23120, Thailand",
    province: "Trat",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 80,
    totalConnectors: 4,
    availableConnectors: 1,
    priceText: "THB 8.00/kWh",
    openingHours: { summary: "6:00 AM - 9:00 PM" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.1,
    ratingCount: 24,
    confidenceScore: 0.79,
    stale: false,
  },
  {
    id: "charger-korat-terminal21",
    name: "Korat Terminal Charge Hub",
    operatorName: "EA Anywhere",
    location: {
      lat: 14.9809,
      lng: 102.0997,
      address: "Mueang Nakhon Ratchasima, Nakhon Ratchasima 30000, Thailand",
      placeId: "mock-charger-korat-terminal21",
    },
    address: "Mueang Nakhon Ratchasima, Nakhon Ratchasima 30000, Thailand",
    province: "Nakhon Ratchasima",
    connectorTypes: ["CCS2", "CHADEMO", "TYPE2"],
    maxKw: 150,
    totalConnectors: 10,
    availableConnectors: 5,
    priceText: "THB 8.50/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.5,
    ratingCount: 69,
    confidenceScore: 0.93,
    stale: false,
  },
  {
    id: "charger-khon-kaen-central",
    name: "Khon Kaen Central EV Station",
    operatorName: "PEA Volta",
    location: {
      lat: 16.4322,
      lng: 102.8236,
      address: "Mueang Khon Kaen, Khon Kaen 40000, Thailand",
      placeId: "mock-charger-khon-kaen-central",
    },
    address: "Mueang Khon Kaen, Khon Kaen 40000, Thailand",
    province: "Khon Kaen",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 120,
    totalConnectors: 8,
    availableConnectors: 4,
    priceText: "THB 8.20/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.4,
    ratingCount: 56,
    confidenceScore: 0.88,
    stale: false,
  },
  {
    id: "charger-udon-thani-city",
    name: "Udon Thani City Charge",
    operatorName: "VoltWay",
    location: {
      lat: 17.4138,
      lng: 102.7872,
      address: "Mueang Udon Thani, Udon Thani 41000, Thailand",
      placeId: "mock-charger-udon-thani-city",
    },
    address: "Mueang Udon Thani, Udon Thani 41000, Thailand",
    province: "Udon Thani",
    connectorTypes: ["CCS2", "CHADEMO"],
    maxKw: 100,
    totalConnectors: 6,
    availableConnectors: 2,
    priceText: "THB 8.10/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.2,
    ratingCount: 32,
    confidenceScore: 0.81,
    stale: false,
  },
  {
    id: "charger-chiang-mai-nimman",
    name: "Nimman EV Fast Charge",
    operatorName: "EA Anywhere",
    location: {
      lat: 18.7983,
      lng: 98.9671,
      address: "Nimmanhaemin Rd, Chiang Mai 50200, Thailand",
      placeId: "mock-charger-chiang-mai-nimman",
    },
    address: "Nimmanhaemin Rd, Chiang Mai 50200, Thailand",
    province: "Chiang Mai",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 150,
    totalConnectors: 10,
    availableConnectors: 6,
    priceText: "THB 8.60/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.7,
    ratingCount: 88,
    confidenceScore: 0.95,
    stale: false,
  },
  {
    id: "charger-chiang-mai-old-city",
    name: "Old City EV Point",
    operatorName: "PEA Volta",
    location: {
      lat: 18.7883,
      lng: 98.9853,
      address: "Old City, Chiang Mai 50200, Thailand",
      placeId: "mock-charger-chiang-mai-old-city",
    },
    address: "Old City, Chiang Mai 50200, Thailand",
    province: "Chiang Mai",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 80,
    totalConnectors: 6,
    availableConnectors: 3,
    priceText: "THB 7.90/kWh",
    openingHours: { summary: "7:00 AM - 11:00 PM" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.3,
    ratingCount: 44,
    confidenceScore: 0.86,
    stale: false,
  },
  {
    id: "charger-chiang-rai-clock-tower",
    name: "Chiang Rai Clock Tower EV Stop",
    operatorName: "VoltWay",
    location: {
      lat: 19.9072,
      lng: 99.8309,
      address: "Mueang Chiang Rai, Chiang Rai 57000, Thailand",
      placeId: "mock-charger-chiang-rai-clock-tower",
    },
    address: "Mueang Chiang Rai, Chiang Rai 57000, Thailand",
    province: "Chiang Rai",
    connectorTypes: ["CCS2", "CHADEMO"],
    maxKw: 100,
    totalConnectors: 6,
    availableConnectors: 2,
    priceText: "THB 8.20/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.2,
    ratingCount: 27,
    confidenceScore: 0.8,
    stale: false,
  },
  {
    id: "charger-pai-walking-street",
    name: "Pai Walking Street Charge",
    operatorName: "PEA Volta",
    location: {
      lat: 19.3586,
      lng: 98.4406,
      address: "Pai, Mae Hong Son 58130, Thailand",
      placeId: "mock-charger-pai-walking-street",
    },
    address: "Pai, Mae Hong Son 58130, Thailand",
    province: "Mae Hong Son",
    connectorTypes: ["TYPE2"],
    maxKw: 22,
    totalConnectors: 4,
    availableConnectors: 1,
    priceText: "THB 6.50/kWh",
    openingHours: { summary: "8:00 AM - 8:00 PM" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.0,
    ratingCount: 16,
    confidenceScore: 0.74,
    stale: false,
  },
  {
    id: "charger-sukhothai-historical",
    name: "Sukhothai Heritage Charge",
    operatorName: "PEA Volta",
    location: {
      lat: 17.0056,
      lng: 99.823,
      address: "Mueang Kao, Sukhothai 64210, Thailand",
      placeId: "mock-charger-sukhothai-historical",
    },
    address: "Mueang Kao, Sukhothai 64210, Thailand",
    province: "Sukhothai",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 80,
    totalConnectors: 4,
    availableConnectors: 2,
    priceText: "THB 7.80/kWh",
    openingHours: { summary: "7:00 AM - 9:00 PM" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.3,
    ratingCount: 29,
    confidenceScore: 0.9,
    stale: false,
  },
  {
    id: "charger-phitsanulok-city",
    name: "Phitsanulok City EV Hub",
    operatorName: "VoltWay",
    location: {
      lat: 16.8211,
      lng: 100.2659,
      address: "Mueang Phitsanulok, Phitsanulok 65000, Thailand",
      placeId: "mock-charger-phitsanulok-city",
    },
    address: "Mueang Phitsanulok, Phitsanulok 65000, Thailand",
    province: "Phitsanulok",
    connectorTypes: ["CCS2", "CHADEMO", "TYPE2"],
    maxKw: 120,
    totalConnectors: 8,
    availableConnectors: 4,
    priceText: "THB 8.30/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.4,
    ratingCount: 38,
    confidenceScore: 0.87,
    stale: false,
  },
  {
    id: "charger-phuket-patong-beach",
    name: "Patong Beach EV Station",
    operatorName: "EA Anywhere",
    location: {
      lat: 7.8965,
      lng: 98.2966,
      address: "Patong, Kathu, Phuket 83150, Thailand",
      placeId: "mock-charger-phuket-patong-beach",
    },
    address: "Patong, Kathu, Phuket 83150, Thailand",
    province: "Phuket",
    connectorTypes: ["CCS2", "CHADEMO", "TYPE2"],
    maxKw: 150,
    totalConnectors: 10,
    availableConnectors: 5,
    priceText: "THB 8.90/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.6,
    ratingCount: 84,
    confidenceScore: 0.94,
    stale: false,
  },
  {
    id: "charger-phuket-old-town",
    name: "Phuket Old Town Charge Point",
    operatorName: "PEA Volta",
    location: {
      lat: 7.884,
      lng: 98.3923,
      address: "Mueang Phuket, Phuket 83000, Thailand",
      placeId: "mock-charger-phuket-old-town",
    },
    address: "Mueang Phuket, Phuket 83000, Thailand",
    province: "Phuket",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 100,
    totalConnectors: 6,
    availableConnectors: 3,
    priceText: "THB 8.20/kWh",
    openingHours: { summary: "7:00 AM - 11:00 PM" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.4,
    ratingCount: 51,
    confidenceScore: 0.87,
    stale: false,
  },
  {
    id: "charger-krabi-ao-nang",
    name: "Ao Nang EV Fast Stop",
    operatorName: "VoltWay",
    location: {
      lat: 8.0347,
      lng: 98.8242,
      address: "Ao Nang, Krabi 81180, Thailand",
      placeId: "mock-charger-krabi-ao-nang",
    },
    address: "Ao Nang, Krabi 81180, Thailand",
    province: "Krabi",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 120,
    totalConnectors: 6,
    availableConnectors: 2,
    priceText: "THB 8.50/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.3,
    ratingCount: 36,
    confidenceScore: 0.82,
    stale: false,
  },
  {
    id: "charger-surat-thani-city",
    name: "Surat Thani City EV Hub",
    operatorName: "PEA Volta",
    location: {
      lat: 9.1401,
      lng: 99.3331,
      address: "Mueang Surat Thani, Surat Thani 84000, Thailand",
      placeId: "mock-charger-surat-thani-city",
    },
    address: "Mueang Surat Thani, Surat Thani 84000, Thailand",
    province: "Surat Thani",
    connectorTypes: ["CCS2", "CHADEMO", "TYPE2"],
    maxKw: 120,
    totalConnectors: 8,
    availableConnectors: 5,
    priceText: "THB 8.30/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.4,
    ratingCount: 45,
    confidenceScore: 0.91,
    stale: false,
  },
  {
    id: "charger-koh-samui-chaweng",
    name: "Chaweng Beach EV Point",
    operatorName: "EA Anywhere",
    location: {
      lat: 9.532,
      lng: 100.061,
      address: "Chaweng, Ko Samui, Surat Thani 84320, Thailand",
      placeId: "mock-charger-koh-samui-chaweng",
    },
    address: "Chaweng, Ko Samui, Surat Thani 84320, Thailand",
    province: "Surat Thani",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 80,
    totalConnectors: 6,
    availableConnectors: 2,
    priceText: "THB 8.80/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.5,
    ratingCount: 61,
    confidenceScore: 0.86,
    stale: false,
  },
  {
    id: "charger-hat-yai-central",
    name: "Hat Yai Central EV Station",
    operatorName: "PEA Volta",
    location: {
      lat: 7.0086,
      lng: 100.4747,
      address: "Hat Yai, Songkhla 90110, Thailand",
      placeId: "mock-charger-hat-yai-central",
    },
    address: "Hat Yai, Songkhla 90110, Thailand",
    province: "Songkhla",
    connectorTypes: ["CCS2", "CHADEMO", "TYPE2"],
    maxKw: 150,
    totalConnectors: 10,
    availableConnectors: 4,
    priceText: "THB 8.60/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.5,
    ratingCount: 72,
    confidenceScore: 0.93,
    stale: false,
  },
  {
    id: "charger-trang-city",
    name: "Trang City Charge Point",
    operatorName: "VoltWay",
    location: {
      lat: 7.5594,
      lng: 99.6114,
      address: "Mueang Trang, Trang 92000, Thailand",
      placeId: "mock-charger-trang-city",
    },
    address: "Mueang Trang, Trang 92000, Thailand",
    province: "Trang",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 100,
    totalConnectors: 6,
    availableConnectors: 3,
    priceText: "THB 8.10/kWh",
    openingHours: { summary: "7:00 AM - 10:00 PM" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.1,
    ratingCount: 22,
    confidenceScore: 0.78,
    stale: false,
  },
  {
    id: "charger-nakhon-si-thammarat-city",
    name: "Nakhon Si EV Fast Hub",
    operatorName: "PEA Volta",
    location: {
      lat: 8.4325,
      lng: 99.9599,
      address:
        "Mueang Nakhon Si Thammarat, Nakhon Si Thammarat 80000, Thailand",
      placeId: "mock-charger-nakhon-si-thammarat-city",
    },
    address: "Mueang Nakhon Si Thammarat, Nakhon Si Thammarat 80000, Thailand",
    province: "Nakhon Si Thammarat",
    connectorTypes: ["CCS2", "CHADEMO"],
    maxKw: 120,
    totalConnectors: 8,
    availableConnectors: 4,
    priceText: "THB 8.20/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.3,
    ratingCount: 33,
    confidenceScore: 0.85,
    stale: false,
  },
  {
    id: "charger-vientiane-riverside",
    name: "Vientiane Riverside EV Point",
    operatorName: "Mekong Charge",
    location: {
      lat: 17.9637,
      lng: 102.6126,
      address: "Riverside, Vientiane, Laos",
      placeId: "mock-charger-vientiane-riverside",
    },
    address: "Riverside, Vientiane, Laos",
    province: "Vientiane",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 80,
    totalConnectors: 4,
    availableConnectors: 2,
    priceText: "LAK 4,500/kWh",
    openingHours: { summary: "8:00 AM - 9:00 PM" },
    source: "USER_SUBMITTED",
    verificationStatus: "USER_VERIFIED",
    status: "active",
    ratingAvg: 4.0,
    ratingCount: 14,
    confidenceScore: 0.73,
    stale: false,
  },
  {
    id: "charger-siem-reap-angkor",
    name: "Angkor EV Station",
    operatorName: "Mekong Charge",
    location: {
      lat: 13.3671,
      lng: 103.8448,
      address: "Siem Reap, Cambodia",
      placeId: "mock-charger-siem-reap-angkor",
    },
    address: "Siem Reap, Cambodia",
    province: "Siem Reap",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 100,
    totalConnectors: 6,
    availableConnectors: 3,
    priceText: "KHR 1,500/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "GOOGLE_PLACES",
    verificationStatus: "GOOGLE_CACHED",
    status: "active",
    ratingAvg: 4.2,
    ratingCount: 21,
    confidenceScore: 0.8,
    stale: false,
  },
  {
    id: "charger-kuala-lumpur-bukit-bintang",
    name: "Bukit Bintang Rapid Charge",
    operatorName: "ChargeGrid",
    location: {
      lat: 3.1466,
      lng: 101.7116,
      address: "Bukit Bintang, Kuala Lumpur, Malaysia",
      placeId: "mock-charger-kuala-lumpur-bukit-bintang",
    },
    address: "Bukit Bintang, Kuala Lumpur, Malaysia",
    province: "Kuala Lumpur",
    connectorTypes: ["CCS2", "TYPE2"],
    maxKw: 150,
    totalConnectors: 8,
    availableConnectors: 4,
    priceText: "MYR 1.40/kWh",
    openingHours: { summary: "Open 24 hours" },
    source: "ADMIN_IMPORT",
    verificationStatus: "ADMIN_VERIFIED",
    status: "active",
    ratingAvg: 4.5,
    ratingCount: 63,
    confidenceScore: 0.91,
    stale: false,
  },
];

export function searchEvChargers(query: string): EvCharger[] {
  const normalizedQuery = query.trim().toLowerCase();

  if (!normalizedQuery) {
    return mockEvChargers.slice(0, 12);
  }

  return mockEvChargers
    .filter((charger) => {
      const searchableText = [
        charger.name,
        charger.operatorName,
        charger.address,
        charger.province,
        charger.connectorTypes.join(" "),
      ]
        .filter(Boolean)
        .join(" ")
        .toLowerCase();

      return searchableText.includes(normalizedQuery);
    })
    .slice(0, 12);
}

export async function getEvChargersNear({
  lat,
  lng,
  radiusKm = 8,
}: GetEvChargersNearParams): Promise<EvChargerList> {
  const items = mockEvChargers.filter(
    (charger) => getDistanceKm({ lat, lng }, charger.location) <= radiusKm,
  );

  return {
    items,
    meta: {
      source: "local_cache",
      tileKey: `mock_${lat.toFixed(2)}_${lng.toFixed(2)}`,
      stale: items.some((charger) => charger.stale),
      refreshed: false,
    },
  };
}
