import type { MockPlace, PlaceSuggestion } from "./types";

export type { PlaceSuggestion } from "./types";

export const mockPlaceSuggestions: PlaceSuggestion[] = [
  { id: "suggestion-starbucks", label: "Starbucks", searchKey: "starbucks" },
  { id: "suggestion-cafe", label: "Cafe", searchKey: "cafe" },
  { id: "suggestion-temple", label: "Temple", searchKey: "temple" },
  {
    id: "suggestion-night-market",
    label: "Night Market",
    searchKey: "night-market",
  },
  { id: "suggestion-mall", label: "Shopping Mall", searchKey: "mall" },
  { id: "suggestion-beach", label: "Beach", searchKey: "beach" },
  { id: "suggestion-park", label: "Park", searchKey: "park" },
  { id: "suggestion-restaurant", label: "Restaurant", searchKey: "restaurant" },
  { id: "suggestion-hotel", label: "Hotel", searchKey: "hotel" },
  { id: "suggestion-viewpoint", label: "Viewpoint", searchKey: "viewpoint" },
];

export const mockPlaceSearchResults: Record<string, MockPlace[]> = {
  starbucks: [
    {
      id: "starbucks-bkk-1",
      name: "Starbucks CentralWorld",
      description:
        "Popular coffee chain branch inside one of Bangkok’s busiest malls.",
      address: "CentralWorld, Rama I Rd, Pathum Wan, Bangkok 10330, Thailand",
      lat: 13.7466,
      lng: 100.5393,
      rating: 4.4,
      reviewCount: 420,
      category: "Coffee shop",
      priceLevel: "$$",
      openingHours: "Open until 10:00 PM",
      phone: "+66 2-100-0001",
      website: "https://www.starbucks.co.th",
    },
    {
      id: "starbucks-bkk-2",
      name: "Starbucks Siam Paragon",
      description: "Convenient cafe stop in the Siam shopping district.",
      address: "Siam Paragon, Rama I Rd, Pathum Wan, Bangkok 10330, Thailand",
      lat: 13.7461,
      lng: 100.5347,
      rating: 4.5,
      reviewCount: 385,
      category: "Coffee shop",
      priceLevel: "$$",
      openingHours: "Open until 9:30 PM",
      phone: "+66 2-100-0002",
      website: "https://www.starbucks.co.th",
    },
    {
      id: "starbucks-cnx-1",
      name: "Starbucks MAYA Chiang Mai",
      description:
        "Cafe branch near Nimmanhaemin with drinks and light snacks.",
      address: "MAYA Lifestyle Shopping Center, Chiang Mai 50200, Thailand",
      lat: 18.8003,
      lng: 98.9685,
      rating: 4.3,
      reviewCount: 240,
      category: "Coffee shop",
      priceLevel: "$$",
      openingHours: "Open until 9:00 PM",
      phone: "+66 53-100-003",
      website: "https://www.starbucks.co.th",
    },
    {
      id: "starbucks-hkt-1",
      name: "Starbucks Jungceylon Patong",
      description: "Well-known coffee stop in Patong’s shopping area.",
      address: "Jungceylon Shopping Center, Patong, Phuket 83150, Thailand",
      lat: 7.8916,
      lng: 98.3007,
      rating: 4.2,
      reviewCount: 198,
      category: "Coffee shop",
      priceLevel: "$$",
      openingHours: "Open until 10:00 PM",
      phone: "+66 76-100-004",
      website: "https://www.starbucks.co.th",
    },
    {
      id: "starbucks-pattaya-1",
      name: "Starbucks Central Pattaya",
      description:
        "Casual coffee shop for tourists and locals in central Pattaya.",
      address: "Central Pattaya, Pattaya Sai Song Rd, Chonburi 20150, Thailand",
      lat: 12.9346,
      lng: 100.883,
      rating: 4.3,
      reviewCount: 176,
      category: "Coffee shop",
      priceLevel: "$$",
      openingHours: "Open until 9:30 PM",
      phone: "+66 38-100-005",
      website: "https://www.starbucks.co.th",
    },
    {
      id: "starbucks-khon-kaen-1",
      name: "Starbucks Central Khon Kaen",
      description: "Popular cafe stop inside Central Khon Kaen mall.",
      address: "Central Khon Kaen, Khon Kaen 40000, Thailand",
      lat: 16.4326,
      lng: 102.823,
      rating: 4.3,
      reviewCount: 162,
      category: "Coffee shop",
      priceLevel: "$$",
      openingHours: "Open until 9:00 PM",
      phone: "+66 43-100-006",
      website: "https://www.starbucks.co.th",
    },
    {
      id: "starbucks-hat-yai-1",
      name: "Starbucks Central Hat Yai",
      description: "Convenient coffee stop in central Hat Yai.",
      address: "Central Hat Yai, Hat Yai, Songkhla 90110, Thailand",
      lat: 7.0063,
      lng: 100.4742,
      rating: 4.2,
      reviewCount: 148,
      category: "Coffee shop",
      priceLevel: "$$",
      openingHours: "Open until 9:00 PM",
      phone: "+66 74-100-007",
      website: "https://www.starbucks.co.th",
    },
  ],

  cafe: [
    {
      id: "cafe-1",
      name: "After You Dessert Cafe",
      description: "Popular dessert cafe known for honey toast and kakigori.",
      address: "Siam Square One, Bangkok 10330, Thailand",
      lat: 13.7457,
      lng: 100.5333,
      rating: 4.6,
      reviewCount: 550,
      category: "Cafe",
      priceLevel: "$$",
      openingHours: "Open until 10:00 PM",
      phone: "+66 2-100-0101",
    },
    {
      id: "cafe-2",
      name: "Ristr8to Lab",
      description: "Specialty coffee spot famous in Chiang Mai.",
      address: "Nimmanhaemin Rd, Suthep, Chiang Mai 50200, Thailand",
      lat: 18.7969,
      lng: 98.9687,
      rating: 4.7,
      reviewCount: 690,
      category: "Cafe",
      priceLevel: "$$",
      openingHours: "Open until 6:00 PM",
      phone: "+66 53-100-0102",
    },
    {
      id: "cafe-3",
      name: "The Coffee Club Patong",
      description: "Relaxed all-day cafe with coffee and breakfast dishes.",
      address: "Thaweewong Rd, Patong, Phuket 83150, Thailand",
      lat: 7.8964,
      lng: 98.2957,
      rating: 4.3,
      reviewCount: 201,
      category: "Cafe",
      priceLevel: "$$",
      openingHours: "Open until 9:00 PM",
      phone: "+66 76-100-0103",
    },
    {
      id: "cafe-4",
      name: "BluPort Coffee Corner",
      description: "Modern cafe stop in Hua Hin shopping complex.",
      address:
        "BluPort Hua Hin, Phetkasem Rd, Prachuap Khiri Khan 77110, Thailand",
      lat: 12.5481,
      lng: 99.9616,
      rating: 4.2,
      reviewCount: 97,
      category: "Cafe",
      priceLevel: "$$",
      openingHours: "Open until 8:00 PM",
      phone: "+66 32-100-0104",
    },
    {
      id: "cafe-5",
      name: "GRAPH Cafe",
      description: "Minimalist coffee shop known for slow bar brews.",
      address: "Nimmanhaemin Rd, Chiang Mai 50200, Thailand",
      lat: 18.7962,
      lng: 98.9679,
      rating: 4.6,
      reviewCount: 420,
      category: "Cafe",
      priceLevel: "$$",
      openingHours: "Open until 6:00 PM",
      phone: "+66 53-100-0105",
    },
    {
      id: "cafe-6",
      name: "Factory Coffee Bangkok",
      description: "Specialty coffee bar with signature cold brew drinks.",
      address: "Phaya Thai Rd, Ratchathewi, Bangkok 10400, Thailand",
      lat: 13.7562,
      lng: 100.5332,
      rating: 4.5,
      reviewCount: 310,
      category: "Cafe",
      priceLevel: "$$",
      openingHours: "Open until 7:00 PM",
      phone: "+66 2-100-0106",
    },
  ],

  temple: [
    {
      id: "temple-1",
      name: "Wat Arun",
      description: "Iconic riverside temple with a striking central prang.",
      address: "158 Wang Doem Rd, Bangkok Yai, Bangkok 10600, Thailand",
      lat: 13.7437,
      lng: 100.4889,
      rating: 4.8,
      reviewCount: 12400,
      category: "Temple",
      priceLevel: "$",
      openingHours: "Open until 6:00 PM",
      website: "https://www.watarun1.com",
    },
    {
      id: "temple-2",
      name: "Wat Pho",
      description: "Historic temple complex famous for the Reclining Buddha.",
      address: "2 Sanamchai Rd, Phra Nakhon, Bangkok 10200, Thailand",
      lat: 13.7465,
      lng: 100.493,
      rating: 4.8,
      reviewCount: 15800,
      category: "Temple",
      priceLevel: "$",
      openingHours: "Open until 6:30 PM",
    },
    {
      id: "temple-3",
      name: "Wat Phra That Doi Suthep",
      description: "Sacred mountaintop temple overlooking Chiang Mai.",
      address: "Suthep, Mueang Chiang Mai, Chiang Mai 50200, Thailand",
      lat: 18.8048,
      lng: 98.9215,
      rating: 4.8,
      reviewCount: 9900,
      category: "Temple",
      priceLevel: "$",
      openingHours: "Open until 5:30 PM",
    },
    {
      id: "temple-4",
      name: "Wat Mahathat",
      description:
        "Historic Ayutthaya temple ruins with iconic Buddha head in tree roots.",
      address: "Ayutthaya Historical Park, Ayutthaya 13000, Thailand",
      lat: 14.3553,
      lng: 100.5683,
      rating: 4.7,
      reviewCount: 6300,
      category: "Temple",
      priceLevel: "$",
      openingHours: "Open until 5:00 PM",
    },
    {
      id: "temple-5",
      name: "Wat Rong Khun",
      description: "White Temple landmark with intricate modern art design.",
      address: "Pa O Don Chai, Chiang Rai 57000, Thailand",
      lat: 19.8244,
      lng: 99.7634,
      rating: 4.7,
      reviewCount: 15400,
      category: "Temple",
      priceLevel: "$",
      openingHours: "Open until 5:30 PM",
    },
    {
      id: "temple-6",
      name: "Wat Phra That Hariphunchai",
      description: "Historic Lamphun temple with golden chedi.",
      address: "Mueang Lamphun, Lamphun 51000, Thailand",
      lat: 18.5771,
      lng: 99.0065,
      rating: 4.7,
      reviewCount: 3300,
      category: "Temple",
      priceLevel: "$",
      openingHours: "Open until 5:00 PM",
    },
  ],

  "night-market": [
    {
      id: "market-1",
      name: "Jodd Fairs Night Market",
      description:
        "Popular Bangkok night market with food stalls and shopping.",
      address: "Rama IX Rd, Huai Khwang, Bangkok 10310, Thailand",
      lat: 13.7577,
      lng: 100.5664,
      rating: 4.5,
      reviewCount: 4900,
      category: "Night market",
      priceLevel: "$$",
      openingHours: "Open until 12:00 AM",
    },
    {
      id: "market-2",
      name: "Chiang Mai Night Bazaar",
      description: "Bustling market for food, souvenirs, and local crafts.",
      address: "Chang Khlan Rd, Chiang Mai 50100, Thailand",
      lat: 18.7877,
      lng: 99.0018,
      rating: 4.4,
      reviewCount: 7200,
      category: "Night market",
      priceLevel: "$$",
      openingHours: "Open until 11:00 PM",
    },
    {
      id: "market-3",
      name: "Phuket Weekend Night Market",
      description: "Large weekend market with snacks, clothes, and souvenirs.",
      address: "Chao Fa West Rd, Phuket 83000, Thailand",
      lat: 7.8804,
      lng: 98.3676,
      rating: 4.4,
      reviewCount: 3800,
      category: "Night market",
      priceLevel: "$$",
      openingHours: "Open until 10:00 PM",
    },
    {
      id: "market-4",
      name: "Thepprasit Night Market",
      description: "Popular Pattaya market known for street food and bargains.",
      address: "Thepprasit Rd, Pattaya, Chonburi 20150, Thailand",
      lat: 12.9098,
      lng: 100.8907,
      rating: 4.3,
      reviewCount: 2400,
      category: "Night market",
      priceLevel: "$$",
      openingHours: "Open until 11:00 PM",
    },
    {
      id: "market-5",
      name: "Asiatique The Riverfront",
      description: "Open-air riverfront market with shops and dining.",
      address: "2194 Charoen Krung Rd, Bang Kho Laem, Bangkok 10120, Thailand",
      lat: 13.7049,
      lng: 100.5034,
      rating: 4.5,
      reviewCount: 14500,
      category: "Night market",
      priceLevel: "$$",
      openingHours: "Open until 12:00 AM",
    },
    {
      id: "market-6",
      name: "Chiang Rai Night Bazaar",
      description: "Night market with street food and local crafts.",
      address: "Chiang Rai 57000, Thailand",
      lat: 19.9106,
      lng: 99.8385,
      rating: 4.3,
      reviewCount: 2100,
      category: "Night market",
      priceLevel: "$$",
      openingHours: "Open until 11:00 PM",
    },
  ],

  mall: [
    {
      id: "mall-1",
      name: "ICONSIAM",
      description:
        "Luxury riverside mall with shopping, dining, and attractions.",
      address: "299 Charoen Nakhon Rd, Khlong San, Bangkok 10600, Thailand",
      lat: 13.7262,
      lng: 100.51,
      rating: 4.7,
      reviewCount: 21500,
      category: "Shopping mall",
      priceLevel: "$$$",
      openingHours: "Open until 10:00 PM",
      website: "https://www.iconsiam.com",
    },
    {
      id: "mall-2",
      name: "Siam Paragon",
      description: "Premium shopping destination in the heart of Bangkok.",
      address: "991 Rama I Rd, Pathum Wan, Bangkok 10330, Thailand",
      lat: 13.7461,
      lng: 100.5347,
      rating: 4.7,
      reviewCount: 19800,
      category: "Shopping mall",
      priceLevel: "$$$",
      openingHours: "Open until 10:00 PM",
    },
    {
      id: "mall-3",
      name: "Central Festival Chiang Mai",
      description: "Large shopping center with retail, food, and cinema.",
      address: "Superhighway Chiang Mai-Lampang Rd, Chiang Mai 50000, Thailand",
      lat: 18.8083,
      lng: 99.0171,
      rating: 4.5,
      reviewCount: 8400,
      category: "Shopping mall",
      priceLevel: "$$",
      openingHours: "Open until 10:00 PM",
    },
    {
      id: "mall-4",
      name: "Jungceylon",
      description: "Busy mall in Patong with restaurants and entertainment.",
      address: "Rat U Thit 200 Pee Rd, Patong, Phuket 83150, Thailand",
      lat: 7.8915,
      lng: 98.3006,
      rating: 4.3,
      reviewCount: 9300,
      category: "Shopping mall",
      priceLevel: "$$",
      openingHours: "Open until 10:00 PM",
    },
    {
      id: "mall-5",
      name: "Terminal 21 Pattaya",
      description: "Travel-themed mall with dining and entertainment.",
      address: "456 Pattaya N Rd, Pattaya, Chonburi 20150, Thailand",
      lat: 12.9545,
      lng: 100.8879,
      rating: 4.6,
      reviewCount: 11200,
      category: "Shopping mall",
      priceLevel: "$$",
      openingHours: "Open until 10:00 PM",
    },
    {
      id: "mall-6",
      name: "Central Phuket Floresta",
      description: "Large shopping complex with dining and cinema options.",
      address: "Wichit, Mueang Phuket, Phuket 83000, Thailand",
      lat: 7.8933,
      lng: 98.3685,
      rating: 4.6,
      reviewCount: 8400,
      category: "Shopping mall",
      priceLevel: "$$$",
      openingHours: "Open until 10:00 PM",
    },
  ],

  beach: [
    {
      id: "beach-1",
      name: "Patong Beach",
      description: "One of Phuket’s most famous beaches with nightlife nearby.",
      address: "Patong, Kathu, Phuket 83150, Thailand",
      lat: 7.8965,
      lng: 98.2951,
      rating: 4.4,
      reviewCount: 12100,
      category: "Beach",
      priceLevel: "$",
      openingHours: "Open 24 hours",
    },
    {
      id: "beach-2",
      name: "Railay Beach",
      description: "Scenic beach known for limestone cliffs and clear water.",
      address: "Ao Nang, Krabi 81000, Thailand",
      lat: 8.0053,
      lng: 98.8382,
      rating: 4.8,
      reviewCount: 8700,
      category: "Beach",
      priceLevel: "$",
      openingHours: "Open 24 hours",
    },
    {
      id: "beach-3",
      name: "Kata Beach",
      description:
        "Family-friendly Phuket beach popular for swimming and sunsets.",
      address: "Kata, Karon, Phuket 83100, Thailand",
      lat: 7.8207,
      lng: 98.2982,
      rating: 4.6,
      reviewCount: 6100,
      category: "Beach",
      priceLevel: "$",
      openingHours: "Open 24 hours",
    },
    {
      id: "beach-4",
      name: "Jomtien Beach",
      description:
        "Long beach south of Pattaya with casual seaside atmosphere.",
      address: "Jomtien, Pattaya, Chonburi 20150, Thailand",
      lat: 12.8842,
      lng: 100.8839,
      rating: 4.2,
      reviewCount: 4100,
      category: "Beach",
      priceLevel: "$",
      openingHours: "Open 24 hours",
    },
    {
      id: "beach-5",
      name: "Chaweng Beach",
      description: "Popular Ko Samui beach with white sand and nightlife.",
      address: "Chaweng, Ko Samui, Surat Thani 84320, Thailand",
      lat: 9.5275,
      lng: 100.0616,
      rating: 4.5,
      reviewCount: 9200,
      category: "Beach",
      priceLevel: "$",
      openingHours: "Open 24 hours",
    },
    {
      id: "beach-6",
      name: "Klong Dao Beach",
      description: "Long sandy beach on Koh Lanta with calm waters.",
      address: "Sala Dan, Ko Lanta, Krabi 81150, Thailand",
      lat: 7.6212,
      lng: 99.0365,
      rating: 4.6,
      reviewCount: 3600,
      category: "Beach",
      priceLevel: "$",
      openingHours: "Open 24 hours",
    },
  ],

  park: [
    {
      id: "park-1",
      name: "Lumphini Park",
      description: "Large central Bangkok park great for walking and relaxing.",
      address: "Rama IV Rd, Lumphini, Pathum Wan, Bangkok 10330, Thailand",
      lat: 13.7306,
      lng: 100.5418,
      rating: 4.7,
      reviewCount: 9800,
      category: "Park",
      priceLevel: "$",
      openingHours: "Open until 9:00 PM",
    },
    {
      id: "park-2",
      name: "Benjakitti Park",
      description: "Modern urban park with lake views and cycling paths.",
      address: "Ratchadaphisek Rd, Khlong Toei, Bangkok 10110, Thailand",
      lat: 13.7315,
      lng: 100.5597,
      rating: 4.8,
      reviewCount: 7200,
      category: "Park",
      priceLevel: "$",
      openingHours: "Open until 9:00 PM",
    },
    {
      id: "park-3",
      name: "Nong Buak Haad Public Park",
      description: "Relaxing city park in Chiang Mai’s old town area.",
      address: "Arak Rd, Phra Sing, Chiang Mai 50200, Thailand",
      lat: 18.7806,
      lng: 98.9817,
      rating: 4.5,
      reviewCount: 1500,
      category: "Park",
      priceLevel: "$",
      openingHours: "Open until 8:00 PM",
    },
    {
      id: "park-4",
      name: "Queen Sirikit Park",
      description: "Botanical park with gardens and cycling paths.",
      address: "Chatuchak, Bangkok 10900, Thailand",
      lat: 13.8106,
      lng: 100.5542,
      rating: 4.7,
      reviewCount: 4300,
      category: "Park",
      priceLevel: "$",
      openingHours: "Open until 7:00 PM",
    },
    {
      id: "park-5",
      name: "Suan Luang Rama IX Park",
      description: "Large public park with lake and jogging paths.",
      address: "Prawet, Bangkok 10250, Thailand",
      lat: 13.6894,
      lng: 100.6577,
      rating: 4.6,
      reviewCount: 5200,
      category: "Park",
      priceLevel: "$",
      openingHours: "Open until 7:00 PM",
    },
  ],

  restaurant: [
    {
      id: "restaurant-1",
      name: "Thipsamai Pad Thai",
      description: "Famous Bangkok restaurant known for classic pad thai.",
      address: "313 Maha Chai Rd, Samran Rat, Bangkok 10200, Thailand",
      lat: 13.753,
      lng: 100.5015,
      rating: 4.5,
      reviewCount: 11300,
      category: "Restaurant",
      priceLevel: "$$",
      openingHours: "Open until 12:00 AM",
    },
    {
      id: "restaurant-2",
      name: "Savoey Seafood",
      description: "Well-known Thai seafood restaurant popular with travelers.",
      address: "Mercury Ville, Chidlom, Bangkok 10330, Thailand",
      lat: 13.7447,
      lng: 100.5441,
      rating: 4.4,
      reviewCount: 2900,
      category: "Restaurant",
      priceLevel: "$$$",
      openingHours: "Open until 10:00 PM",
    },
    {
      id: "restaurant-3",
      name: "Tong Tem Toh",
      description: "Popular northern Thai restaurant in Chiang Mai.",
      address: "Nimmanhaemin Soi 13, Chiang Mai 50200, Thailand",
      lat: 18.7964,
      lng: 98.9674,
      rating: 4.5,
      reviewCount: 4100,
      category: "Restaurant",
      priceLevel: "$$",
      openingHours: "Open until 9:00 PM",
    },
    {
      id: "restaurant-4",
      name: "Kan Eang @ Pier",
      description: "Seaside Phuket restaurant known for Thai seafood dishes.",
      address: "Ao Chalong, Phuket 83130, Thailand",
      lat: 7.8296,
      lng: 98.3338,
      rating: 4.5,
      reviewCount: 2700,
      category: "Restaurant",
      priceLevel: "$$$",
      openingHours: "Open until 10:00 PM",
    },
    {
      id: "restaurant-5",
      name: "Krua Apsorn",
      description: "Beloved Bangkok spot for classic Thai comfort dishes.",
      address: "Samsen Rd, Phra Nakhon, Bangkok 10200, Thailand",
      lat: 13.7651,
      lng: 100.5047,
      rating: 4.6,
      reviewCount: 6400,
      category: "Restaurant",
      priceLevel: "$$",
      openingHours: "Open until 8:30 PM",
    },
    {
      id: "restaurant-6",
      name: "Krua Khun Toi",
      description: "Local favorite for Isan flavors and grilled meats.",
      address: "Nai Mueang, Khon Kaen 40000, Thailand",
      lat: 16.4411,
      lng: 102.8358,
      rating: 4.4,
      reviewCount: 1200,
      category: "Restaurant",
      priceLevel: "$$",
      openingHours: "Open until 9:00 PM",
    },
    {
      id: "restaurant-7",
      name: "Chokdee Dim Sum",
      description: "Popular Hat Yai dim sum breakfast spot.",
      address: "Hat Yai, Songkhla 90110, Thailand",
      lat: 7.0112,
      lng: 100.4747,
      rating: 4.5,
      reviewCount: 1900,
      category: "Restaurant",
      priceLevel: "$$",
      openingHours: "Open until 2:00 PM",
    },
  ],

  hotel: [
    {
      id: "hotel-1",
      name: "Mandarin Hotel Bangkok",
      description: "Central Bangkok hotel near transport and shopping areas.",
      address: "662 Rama IV Rd, Maha Phruttharam, Bangkok 10500, Thailand",
      lat: 13.7348,
      lng: 100.5231,
      rating: 4.3,
      reviewCount: 3200,
      category: "Hotel",
      priceLevel: "$$$",
      openingHours: "Open 24 hours",
      phone: "+66 2-100-0301",
    },
    {
      id: "hotel-2",
      name: "U Nimman Chiang Mai",
      description:
        "Stylish hotel in the Nimman area close to cafes and shopping.",
      address: "Nimmanhaemin Rd, Chiang Mai 50200, Thailand",
      lat: 18.7967,
      lng: 98.9681,
      rating: 4.6,
      reviewCount: 1700,
      category: "Hotel",
      priceLevel: "$$$",
      openingHours: "Open 24 hours",
      phone: "+66 53-100-0302",
    },
    {
      id: "hotel-3",
      name: "Holiday Inn Resort Phuket",
      description:
        "Beachside resort in Patong with family-friendly facilities.",
      address: "52 Thaweewong Rd, Patong, Phuket 83150, Thailand",
      lat: 7.8858,
      lng: 98.2937,
      rating: 4.5,
      reviewCount: 2600,
      category: "Hotel",
      priceLevel: "$$$",
      openingHours: "Open 24 hours",
      phone: "+66 76-100-0303",
    },
    {
      id: "hotel-4",
      name: "Hilton Pattaya",
      description: "Modern beachfront hotel with skybar and pool views.",
      address: "333/101 Moo 9, Pattaya, Chonburi 20260, Thailand",
      lat: 12.9344,
      lng: 100.8832,
      rating: 4.6,
      reviewCount: 4100,
      category: "Hotel",
      priceLevel: "$$$$",
      openingHours: "Open 24 hours",
      phone: "+66 38-100-0304",
    },
    {
      id: "hotel-5",
      name: "Rayavadee Krabi",
      description: "Luxury resort near Railay Beach with tropical gardens.",
      address: "Ao Nang, Krabi 81000, Thailand",
      lat: 8.0087,
      lng: 98.8347,
      rating: 4.7,
      reviewCount: 1800,
      category: "Hotel",
      priceLevel: "$$$$",
      openingHours: "Open 24 hours",
      phone: "+66 75-100-0305",
    },
    {
      id: "hotel-6",
      name: "Le Meridien Chiang Rai Resort",
      description: "Riverside resort with spa and garden pools.",
      address: "Mueang Chiang Rai, Chiang Rai 57100, Thailand",
      lat: 19.9262,
      lng: 99.8515,
      rating: 4.6,
      reviewCount: 1300,
      category: "Hotel",
      priceLevel: "$$$$",
      openingHours: "Open 24 hours",
      phone: "+66 53-100-0306",
    },
  ],

  viewpoint: [
    {
      id: "viewpoint-1",
      name: "Khao Rang Viewpoint",
      description: "Popular Phuket viewpoint with panoramic town views.",
      address: "Khao Rang, Phuket Town 83000, Thailand",
      lat: 7.8962,
      lng: 98.3854,
      rating: 4.5,
      reviewCount: 2100,
      category: "Viewpoint",
      priceLevel: "$",
      openingHours: "Open until 10:00 PM",
    },
    {
      id: "viewpoint-2",
      name: "Samet Nangshe Viewpoint",
      description: "Scenic viewpoint overlooking Phang Nga Bay.",
      address: "Khlong Khian, Takua Thung, Phang Nga 82130, Thailand",
      lat: 8.2403,
      lng: 98.4503,
      rating: 4.8,
      reviewCount: 3500,
      category: "Viewpoint",
      priceLevel: "$",
      openingHours: "Open until 6:00 PM",
    },
    {
      id: "viewpoint-3",
      name: "Pattaya Viewpoint",
      description: "Classic lookout spot above Pattaya Bay.",
      address: "Pratumnak Hill, Pattaya, Chonburi 20150, Thailand",
      lat: 12.9158,
      lng: 100.8597,
      rating: 4.4,
      reviewCount: 2800,
      category: "Viewpoint",
      priceLevel: "$",
      openingHours: "Open until 9:00 PM",
    },
    {
      id: "viewpoint-4",
      name: "Promthep Cape Viewpoint",
      description: "Phuket sunset viewpoint with panoramic sea views.",
      address: "Rawai, Mueang Phuket, Phuket 83130, Thailand",
      lat: 7.7613,
      lng: 98.3067,
      rating: 4.7,
      reviewCount: 6900,
      category: "Viewpoint",
      priceLevel: "$",
      openingHours: "Open until 7:00 PM",
    },
    {
      id: "viewpoint-5",
      name: "Doi Inthanon Summit View",
      description: "High-altitude viewpoint at Thailand's highest peak.",
      address: "Doi Inthanon National Park, Chiang Mai 50270, Thailand",
      lat: 18.5887,
      lng: 98.4869,
      rating: 4.8,
      reviewCount: 4100,
      category: "Viewpoint",
      priceLevel: "$",
      openingHours: "Open until 6:00 PM",
    },
    {
      id: "viewpoint-6",
      name: "Khao Sok Viewpoint",
      description: "Scenic viewpoint over rainforest and limestone peaks.",
      address: "Khao Sok, Phanom, Surat Thani 84250, Thailand",
      lat: 8.9106,
      lng: 98.5362,
      rating: 4.6,
      reviewCount: 1200,
      category: "Viewpoint",
      priceLevel: "$",
      openingHours: "Open until 6:00 PM",
    },
  ],
};

export function getPlaceSuggestions(query: string): PlaceSuggestion[] {
  const normalizedQuery = query.trim().toLowerCase();

  if (!normalizedQuery) {
    return [];
  }

  return mockPlaceSuggestions.filter((suggestion) =>
    suggestion.label.toLowerCase().includes(normalizedQuery),
  );
}

export function getPlaceResults(searchKey: string): MockPlace[] {
  return mockPlaceSearchResults[searchKey] ?? [];
}

export function getDistanceKm(
  from: { lat: number; lng: number },
  to: { lat: number; lng: number },
): number {
  const earthRadiusKm = 6371;
  const latDelta = ((to.lat - from.lat) * Math.PI) / 180;
  const lngDelta = ((to.lng - from.lng) * Math.PI) / 180;
  const fromLat = (from.lat * Math.PI) / 180;
  const toLat = (to.lat * Math.PI) / 180;
  const haversine =
    Math.sin(latDelta / 2) * Math.sin(latDelta / 2) +
    Math.cos(fromLat) *
      Math.cos(toLat) *
      Math.sin(lngDelta / 2) *
      Math.sin(lngDelta / 2);

  return (
    earthRadiusKm *
    2 *
    Math.atan2(Math.sqrt(haversine), Math.sqrt(1 - haversine))
  );
}
